title: WorkingHours
modelClass: Doctor\Appointments\Models\WorkingHours
list: $/doctor/appointments/models/workinghours/columns.yaml
recordUrl: 'doctor/appointments/schedule/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'

